-- MySQL Script generated by MySQL Workbench
-- Thu Jul 31 20:37:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chef_up
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chef_up
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chef_up` DEFAULT CHARACTER SET utf8 ;
USE `chef_up` ;

-- -----------------------------------------------------
-- Table `chef_up`.`pronomes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`pronomes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `senha_hash` TEXT NOT NULL,
  `data_cadastro` DATE NOT NULL,
  `pronomes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_pronomes1_idx` (`pronomes_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_pronomes1`
    FOREIGN KEY (`pronomes_id`)
    REFERENCES `chef_up`.`pronomes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`ingredientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `categoria` TEXT NOT NULL,
  `estimativa_validade` INT NOT NULL,
  `dica_conservacao` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`estoque_virtual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`estoque_virtual` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `ingredientes_id` INT NOT NULL,
  `data_adicionada` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estoque_virtual_usuarios_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_estoque_virtual_ingredientes1_idx` (`ingredientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_virtual_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_virtual_ingredientes1`
    FOREIGN KEY (`ingredientes_id`)
    REFERENCES `chef_up`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `icone_url` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`receitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`receitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `descricao` TEXT NOT NULL,
  `tempo_preparo_segundos` INT NOT NULL,
  `dificuldade` TEXT NOT NULL,
  `xp_ganho` INT NOT NULL,
  `categorias_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receitas_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_receitas_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `chef_up`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`ingrediente_receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`ingrediente_receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ingrediente_id` INT NOT NULL,
  `receita_id` INT NOT NULL,
  `unidade_medida` TEXT NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  INDEX `fk_ingrediente_has_receita_receita1_idx` (`receita_id` ASC) VISIBLE,
  INDEX `fk_ingrediente_has_receita_ingrediente1_idx` (`ingrediente_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ingrediente_has_receita_ingrediente1`
    FOREIGN KEY (`ingrediente_id`)
    REFERENCES `chef_up`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingrediente_has_receita_receita1`
    FOREIGN KEY (`receita_id`)
    REFERENCES `chef_up`.`receitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`adjetivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`adjetivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`titulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`titulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `condicao_desbloqueio` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`receita_passo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`receita_passo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ordem` INT NOT NULL,
  `conteudo` TEXT NOT NULL,
  `receitas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receita_passo_receitas1_idx` (`receitas_id` ASC) VISIBLE,
  CONSTRAINT `fk_receita_passo_receitas1`
    FOREIGN KEY (`receitas_id`)
    REFERENCES `chef_up`.`receitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`avatares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`avatares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `imagem_url` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`titulo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`titulo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `desbloqueado_em` DATE NULL,
  INDEX `fk_table1_titulos1_idx` (`titulos_id` ASC) VISIBLE,
  INDEX `fk_table1_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_titulos1`
    FOREIGN KEY (`titulos_id`)
    REFERENCES `chef_up`.`titulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`adjetivo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`adjetivo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adjetivos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  INDEX `fk_table1_adjetivos1_idx` (`adjetivos_id` ASC) VISIBLE,
  INDEX `fk_table1_usuarios2_idx` (`usuarios_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_adjetivos1`
    FOREIGN KEY (`adjetivos_id`)
    REFERENCES `chef_up`.`adjetivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_usuarios2`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`avatar_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`avatar_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `avatares_id` INT NOT NULL,
  `desbloqueado_em` DATE NULL,
  INDEX `fk_table1_usuarios3_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_table1_avatares1_idx` (`avatares_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_usuarios3`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_avatares1`
    FOREIGN KEY (`avatares_id`)
    REFERENCES `chef_up`.`avatares` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`receita_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`receita_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `receitas_id` INT NOT NULL,
  `data_criacao` DATE NOT NULL,
  `foto_prato` TEXT NOT NULL,
  `pontuacao_prato` INT NOT NULL,
  INDEX `fk_receita_usuario_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_receita_usuario_receitas1_idx` (`receitas_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_receita_usuario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_usuario_receitas1`
    FOREIGN KEY (`receitas_id`)
    REFERENCES `chef_up`.`receitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`progresso_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`progresso_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `nivel` INT NOT NULL,
  `xp` INT NOT NULL,
  `atualizado_em` DATE NOT NULL,
  INDEX `fk_niveis_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_niveis_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`utensilios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`utensilios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`utensilios_receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`utensilios_receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utensilios_id` INT NOT NULL,
  `receitas_id` INT NOT NULL,
  INDEX `fk_utensilios_receita_utensilios1_idx` (`utensilios_id` ASC) VISIBLE,
  INDEX `fk_utensilios_receita_receitas1_idx` (`receitas_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_utensilios_receita_utensilios1`
    FOREIGN KEY (`utensilios_id`)
    REFERENCES `chef_up`.`utensilios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utensilios_receita_receitas1`
    FOREIGN KEY (`receitas_id`)
    REFERENCES `chef_up`.`receitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`colecoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`colecoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_colecoes_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_colecoes_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`colecao_receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`colecao_receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `receitas_id` INT NOT NULL,
  `colecoes_id` INT NOT NULL,
  INDEX `fk_table1_receitas1_idx` (`receitas_id` ASC) VISIBLE,
  INDEX `fk_table1_colecoes1_idx` (`colecoes_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_receitas1`
    FOREIGN KEY (`receitas_id`)
    REFERENCES `chef_up`.`receitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_colecoes1`
    FOREIGN KEY (`colecoes_id`)
    REFERENCES `chef_up`.`colecoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
