-- MySQL Script generated by MySQL Workbench
-- Thu Aug 14 21:26:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chef_up
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chef_up
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chef_up` DEFAULT CHARACTER SET utf8 ;
USE `chef_up` ;

-- -----------------------------------------------------
-- Table `chef_up`.`pronome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`pronome` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `senha_hash` TEXT NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `pronomes_id` INT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_pronomes1_idx` (`pronomes_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_pronomes1`
    FOREIGN KEY (`pronomes_id`)
    REFERENCES `chef_up`.`pronome` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`ingrediente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `categoria` TEXT NOT NULL,
  `estimativa_validade` INT NOT NULL,
  `dica_conservacao` TEXT NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`ingrediente_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`ingrediente_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `ingredientes_id` INT NOT NULL,
  `data_adicionada` DATETIME NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estoque_virtual_usuarios_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_estoque_virtual_ingredientes1_idx` (`ingredientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_virtual_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_virtual_ingredientes1`
    FOREIGN KEY (`ingredientes_id`)
    REFERENCES `chef_up`.`ingrediente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `icone_url` TEXT NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `descricao` TEXT NOT NULL,
  `tempo_preparo_segundos` INT NOT NULL,
  `dificuldade` TEXT NOT NULL,
  `xp_ganho` INT NOT NULL,
  `categorias_id` INT NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receitas_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_receitas_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `chef_up`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`ingrediente_receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`ingrediente_receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ingredientes_id` INT NOT NULL,
  `receitas_id` INT NOT NULL,
  `unidade_medida` TEXT NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  `version` INT NOT NULL,
  INDEX `fk_ingrediente_has_receita_receita1_idx` (`receitas_id` ASC) VISIBLE,
  INDEX `fk_ingrediente_has_receita_ingrediente1_idx` (`ingredientes_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ingrediente_has_receita_ingrediente1`
    FOREIGN KEY (`ingredientes_id`)
    REFERENCES `chef_up`.`ingrediente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingrediente_has_receita_receita1`
    FOREIGN KEY (`receitas_id`)
    REFERENCES `chef_up`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`adjetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`adjetivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`titulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `condicao_desbloqueio` TEXT NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`etapa_receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`etapa_receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ordem` INT NOT NULL,
  `conteudo` TEXT NOT NULL,
  `receitas_id` INT NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receita_passo_receitas1_idx` (`receitas_id` ASC) VISIBLE,
  CONSTRAINT `fk_receita_passo_receitas1`
    FOREIGN KEY (`receitas_id`)
    REFERENCES `chef_up`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`avatar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `imagem_url` TEXT NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`titulo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`titulo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `desbloqueado_em` DATETIME NULL,
  `version` INT NOT NULL,
  INDEX `fk_table1_titulos1_idx` (`titulos_id` ASC) VISIBLE,
  INDEX `fk_table1_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_titulos1`
    FOREIGN KEY (`titulos_id`)
    REFERENCES `chef_up`.`titulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`adjetivo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`adjetivo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adjetivos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `version` INT NOT NULL,
  INDEX `fk_table1_adjetivos1_idx` (`adjetivos_id` ASC) VISIBLE,
  INDEX `fk_table1_usuarios2_idx` (`usuarios_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_adjetivos1`
    FOREIGN KEY (`adjetivos_id`)
    REFERENCES `chef_up`.`adjetivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_usuarios2`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`avatar_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`avatar_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `avatares_id` INT NOT NULL,
  `desbloqueado_em` DATETIME NULL,
  `version` INT NOT NULL,
  INDEX `fk_table1_usuarios3_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_table1_avatares1_idx` (`avatares_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_usuarios3`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_avatares1`
    FOREIGN KEY (`avatares_id`)
    REFERENCES `chef_up`.`avatar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`receita_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`receita_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `receitas_id` INT NOT NULL,
  `data_conclusao` DATETIME NOT NULL,
  `foto_prato` TEXT NOT NULL,
  `pontuacao_prato` INT NOT NULL,
  `version` INT NOT NULL,
  INDEX `fk_receita_usuario_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_receita_usuario_receitas1_idx` (`receitas_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_receita_usuario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_usuario_receitas1`
    FOREIGN KEY (`receitas_id`)
    REFERENCES `chef_up`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`progresso_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`progresso_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `nivel` INT NOT NULL,
  `xp` INT NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `version` INT NOT NULL,
  INDEX `fk_niveis_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_niveis_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`utensilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`utensilio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`utensilio_receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`utensilio_receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utensilios_id` INT NOT NULL,
  `receitas_id` INT NOT NULL,
  `version` INT NOT NULL,
  INDEX `fk_utensilios_receita_utensilios1_idx` (`utensilios_id` ASC) VISIBLE,
  INDEX `fk_utensilios_receita_receitas1_idx` (`receitas_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_utensilios_receita_utensilios1`
    FOREIGN KEY (`utensilios_id`)
    REFERENCES `chef_up`.`utensilio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utensilios_receita_receitas1`
    FOREIGN KEY (`receitas_id`)
    REFERENCES `chef_up`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`colecao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`colecao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_colecoes_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_colecoes_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `chef_up`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chef_up`.`receita_colecao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chef_up`.`receita_colecao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `receitas_id` INT NOT NULL,
  `colecoes_id` INT NOT NULL,
  `version` INT NOT NULL,
  INDEX `fk_table1_receitas1_idx` (`receitas_id` ASC) VISIBLE,
  INDEX `fk_table1_colecoes1_idx` (`colecoes_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_receitas1`
    FOREIGN KEY (`receitas_id`)
    REFERENCES `chef_up`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_colecoes1`
    FOREIGN KEY (`colecoes_id`)
    REFERENCES `chef_up`.`colecao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
